[colors.bright]
black = "0x434758"
blue = "0x9cc4ff"
cyan = "0xa3f7ff"
green = "0xddffa7"
magenta = "0xe1acff"
red = "0xff8b92"
white = "0xffffff"
yellow = "0xffe585"

[colors.normal]
black = "0x282a36"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xd0d0d0"
yellow = "0xffcb6b"

[colors.primary]
background = "0x000000"
foreground = "0xd0d0d0"

[colors.selection]
background = "0x555555"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "MesloEmoji"

[font.bold]
family = "MesloEmoji"

[font.italic]
family = "MesloEmoji"

[font.bold_italic]
family = "MesloEmoji"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.80
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
